### PR TITLE
added dotenv support; added consolidated deployment script with process flow control; updated readme

### PR DESCRIPTION
**Pull request by Speculor**
Added dotenv support. Created consolidated deployment script that allows to deploy all scripts or single components based on .env configuration. Updated Readme.

### CODE REVIEW

**Comment by tzapu** [comment]
hey, great job, worth a mention that https://github.com/BarnBridge/BarnBridge-SmartYieldBonds/pull/63/files should be merged, taken care of in this pull request as well, not sure how to best do that

**Comment by Speculor** [comment]
Trying to get the GitHub actions error "ProviderError: Must be authenticated!" fixed, not a problem with the code, changes are just empty lines.

**Comment by Speculor** [comment]
GitHub action was failing because the BarnBridge-owned Alchemy API key was removed from the config.sample.ts. Not sure if you guys are worried about community members having that API key and using up your quota on Alchemy, or if it's a free or paid account. At any rate, the GitHub Action ("npm i", "npm run compile-and-test") is now succeeding.

**Comment by Speculor** [comment]
@tzapu I think having all the static variables in one place (the .env file) is a better approach. The defaults I put in there are all the latest Kovan contracts so at this point all one has to do to test on Kovan is "npm i" and "npm deploy-from-env". So I think https://github.com/BarnBridge/BarnBridge-SmartYieldBonds/pull/63/files can be closed.

**Pull request merged**
